config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#top'
  get 'home/about' => 'home#about'

  devise_for :users

  #indexからdestroyまでの7つのアクション(RESTfulなURL)
  resources :books

  resources :users, only: [:show, :index, :edit, :update]
  resources :user_image, only: [:edit, :update,:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: {minimum: 2,maximum: 20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:passward,:passward_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name,:passward])
  end

  def after_sign_in_path_for(resource) #login後の遷移
    user_path(resource)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @new_book = Book.new #一覧と投稿を同じページに
    @current_user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end

  def create
    @new_book = Book.new(book_params)

    @new_book.user = current_user
    if @new_book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to book_path(@new_book.id)
    else #createに失敗したとき（titleとopinionどちらか一方でも無しの場合）
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:success] = 'Book was successfully updated.'
      # 詳細画面へリクエスト
      redirect_to book_path(@book.id)
    else # 更新失敗
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])

    if book.destroy
      flash[:success] = 'Book was successfully destroyed.'
      redirect_to books_path
    else
      render edit_book_path(book)
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
    @current_user = current_user
  end

  def index
    @users = User.all
    @current_user = current_user
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])

    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User Info</h2>
<%= attachment_image_tag(user, :profile_image, fallback: "no_image.png", size: "100x100") %>
<table class="table">
<tr></tr>
<tr><th>name</th><td><%= user.name %></td></tr>
<tr></tr>
<tr><th>introduction</th><td><%= user.introduction %></td></tr>
</table>
<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
<% end %>
<h2>New book</h2>
<!-- form_with部分 -->
<%= form_with model: new_book,local: true do |f| %>
    <%# ここからエラーメッセージ %>
    <% if new_book.errors.any? %>
      <%= new_book.errors.count %> errors prohibited this book from being saved:<br>
        <% new_book.errors.full_messages.each do |message| %>
          ・<%= message %><br>
        <% end %>
    <% end %>
    <%# ここまでエラーメッセージ %>
    <div>Title</div>
    <div><%= f.text_field :title %></div>

    <div>Opinion</div>
    <div><%= f.text_area :body%></div>
    <button type="submit" class="btn btn-success">
    <% f.submit %>Create Book
    </button>
<% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>


<!-- form_with部分 -->
<%= form_with model: @book,url:"/books/#{@book.id}", local: true do |f| %>
  <%# ここからエラーメッセージ %>
  <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:<br>
      <% @book.errors.full_messages.each do |message| %>
        ・<%= message %><br>
      <% end %>
  <% end %>
  <%# ここまでエラーメッセージ %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <div><%= f.submit 'Update Book' %></div>

<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= '|' %>
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <!-- 以下を追加 -->
    <div class="col-md-3">
      <!--render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値]-->
      <%= render partial: 'books/list', locals: {user: @current_user , new_book: @new_book, f: @f} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thread>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thread>
        <tbody>
          <!--投稿されたデータ分だけ繰り返す-->
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag(book.user, :profile_image, fallback: "no_image.png" , size: "40x40") %></br>
                <%= book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <!--部分テンプレート-->
            <%= render partial: 'books/list', locals: {user: @user, new_book: @new_book, f: @f} %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
              <table class="table">
                <thread>
                  <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thread>
                <tbody>
                  <tr>
                    <td>
                        <%= link_to user_path(@book.user) do %>
                            <%= attachment_image_tag(@book.user, :profile_image, fallback: "no_image.png" , size: "40x40") %></br>
                            <%= @book.user.name %>
                        <% end %>
                    </td>
                    <td>
                        <%= link_to @book.title, book_path(@book.id) %>
                    </td>
                    <td><%= @book.body %></td>
                    <td>
                        <% if @book.user == current_user %>
                            <%= link_to "Edit", edit_book_path(@book.id) %>
                        <% end %>
                    </td>
                    <td>
                        <% if @book.user == current_user %>
                            <%= link_to "Destroy", book_path(@book), method: :delete %>
                        <% end %>
                    </td>
                  </tr>

                </tbody>
              </table>
        </div>
    </div>
</div>

app/views/home/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to 
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!
      </h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>

      <p>about various books!</p>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <button type="button" class="btn btn-info btn-sm btn-block mb-3 sign_in">
            <%= link_to "Log in", new_user_session_path, class: "hl" %>
          </button>
        </div>
        <div class="row">
          <button type="button" class="btn btn-success btn-sm btn-block sign_up">
            <%= link_to "Sign Up", new_user_registration_path, class: "hl" %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: key %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <!-- FontAwesomeの読み込み -->
    <script src="https://kit.fontawesome.com/66ab8a74a0.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <h1 class="m-0">
          <a class="navbar-brand d-block" href="/">Bookers</a>
        </h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <!--ログアウト機能ここから-->
        <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="fas fa-home nav-link text-light  ml-4 active">
          <!--ログインしているときのHomeの遷移先はuser/id-->
          <%= link_to "Home", user_path(current_user.id), class: "hl"%>
          </li>
          <li class="fas fa-users nav-link text-light ml-4">
          <%= link_to "Users", users_path, class: "hl"%>
          </li>
          <li class="fas fa-book-open nav-link text-light ml-4">
          <%= link_to "Books", books_path, class: "hl" %>
          </li>
          <li class="fas fa-sign-out-alt nav-link text-light ml-4">
          <%= link_to "logout", destroy_user_session_path, method: :delete , class: "hl"%>
          </li>
        </ul>
        <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="fas fa-home nav-link text-light ml-4 active">
          <%= link_to "Home", root_path, class: "hl" %>
          </li>
          <li class="fas fa-link nav-link text-light ml-4">
          <%= link_to "About", home_about_path, class: "hl" %>
          </li>
          <li class="fas fa-user-plus nav-link text-light ml-4">
          <%= link_to "sign up", new_user_registration_path, class: "hl" %>
          </li>
          <li class="fas fa-sign-in-alt nav-link text-light ml-4">
          <%= link_to "login", new_user_session_path, class: "hl" %>
          </li>
        </ul>
        <% end %>
        <!--ログアウト機能ここまで-->
        </div>
      </nav>
    </header>
    <%= render 'layouts/notifications' %>
    <%= yield %>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/edit.html.erb
<h1>User Info</h1>
<!-- form_with部分 -->
<%= form_with model: @user, local: true do |f| %>
  <%# ここからエラーメッセージ %>
  <% if @user.errors.any? %>
    <%= @user.errors.count %> errors prohibited this obj from being saved:<br>
      <% @user.errors.full_messages.each do |message| %>
        ・<%= message %><br>
      <% end %>
  <% end %>
  <h4>name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png"%>
  <label for="inputImage"></label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>

  <h4>introduction</h4>
  <%= f.text_area :introduction %>

  <div><%= f.submit 'Update User' %></div>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <!-- 以下を追加 -->
    <div class="col-md-3">
      <!--部分テンプレート-->
      <%= render partial: 'books/list', locals: {user: @current_user, new_book: @new_book, f: @f} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thread>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thread>
        <tbody>
          <!--投稿されたデータ分だけ繰り返す-->
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag(user, :profile_image, fallback: "no_image.png" , size: "40x40") %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id)%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <!-- 以下を追加 -->
    <div class="col-md-3">
      <!--部分テンプレート-->
      <%= render partial: 'books/list', locals: {user: @user, new_book: @new_book, f: @f} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thread>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
        </thread>
        <tbody>
          <!--投稿されたデータ分だけ繰り返す-->
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag(book.user, :profile_image, fallback: "no_image.png" , size: "40x40") %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>